---
- name: Ensure pymongo is installed for the mongodb_user ansible module
  become: yes
  package:
    name: python-pymongo
    state: present

- name: See if mongodb authorization is enabled and users are configured
  command: 'mongo --eval "db.getUsers()" admin'
  # this will fail (rc 252) if auth is enabled and users are configured
  # With the localhost exception, this will succeed (rc 0) when users are not configured even if auth is enabled.
  # see:
  #   - https://docs.mongodb.com/manual/core/security-users/#localhost-exception
  #   - https://stackoverflow.com/q/31949586/1134951
  #   - https://github.com/ansible/ansible/issues/33832#issuecomment-358031733
  register: _mongo_authorization
  changed_when: no # this does not change anything, it only checks
  failed_when: no # The rc determines whether or not auth is required to create/update the admin user

- name: Show mongodb auth check output
  debug:
    var: _mongo_authorization
    verbosity: 2
