---
- name: Install st2
  hosts: "{{ st2_hosts | default('all') }}"
  environment: "{{ st2_proxy_env | default({}) }}"
  roles:
    - name: Mongo | Main DB for StackStorm
      role: StackStorm.mongodb

    - name: RabbitMQ | Message Broker for StackStorm
      role: StackStorm.rabbitmq

    - name: Postgres | Main DB for StackStorm Mistral
      role: StackStorm.postgresql

    - name: ST2 | Add StackStorm PackageCloud repositories
      role: StackStorm.st2repo

    - name: ST2 | Install and configure StackStorm (st2)
      role: StackStorm.st2

    - name: ST2 | Install and configure st2mistral
      role: StackStorm.st2mistral

    - name: Nginx | Access point for st2web
      role: StackStorm.nginx

    - name: ST2 | Install st2web
      role: StackStorm.st2web

    - name: ST2 | Install st2chatops with node.js and a hubot adapter
      role: StackStorm.st2chatops

    - name: ST2 | Verify StackStorm installation
      role: StackStorm.st2smoketests

    - name: EWC | Install Extreme Workflow Composer (enterprise)
      role: StackStorm.ewc
      when: ewc_license is defined and ewc_license is not none and ewc_license | length > 0

    - name: EWC | Verify Extreme Workflow Composer installation (enterprise)
      role: StackStorm.ewc_smoketests
      when: ewc_license is defined and ewc_license is not none and ewc_license | length > 0