---
- name: Install st2
  hosts: "{{ st2_hosts | default('all') }}"
  roles:
    - name: Mongo | Main DB for StackStorm
      role: mongodb

    - name: RabbitMQ | Message Broker for StackStorm
      role: rabbitmq

    - name: Postgres | Main DB for StackStorm Mistral
      role: postgresql

    - name: ST2 | Add StackStorm PackageCloud repositories
      role: st2repo

    - name: ST2 | Install and configure StackStorm (st2)
      role: st2

    - name: ST2 | Install and configure st2mistral
      role: st2mistral

    - name: Nginx | Access point for st2web
      role: nginx

    - name: ST2 | Install st2web
      role: st2web

    - name: ST2 | Install st2chatops with node.js and a hubot adapter
      role: st2chatops

    - name: ST2 | Verify StackStorm installation
      role: st2smoketests

    - name: EWC | Install Extreme Workflow Composer (enterprise)
      role: ewc
      when: ewc_license is defined and ewc_license is not none

    - name: EWC | Verify Extreme Workflow Composer installation (enterprise)
      role: ewc_smoketests
      when: ewc_license is defined and ewc_license is not none
