---
supported_hubot_adapters:
 - slack
 - hipchat
 - xmpp
 - flowdock
 - yammer
 - spark
 - irc
 - mattermost
 - matteruser
 - shell

# expects the "Get installed st2 version" task to run first.
st2_version_installed: "{{ _st2_version_installed.stdout }}"

# determines which version of node.js to install based on the installed st2
# The key is the st2 version (the newest version not > current version wins)
# The value is the nodejs_major_version to install
st2chatops_nodejs_versions:
  2.4: 6 # >=6, <7
  3.0: 10 # >=8, <11

st2chatops_nodejs_major_version: "{{ st2chatops_nodejs_versions[ st2chatops_nodejs_versions.keys() | sort | reject('version', st2_version_installed, '>') | list | last ] }}"
