---
supported_hubot_adapters:
 - slack
 - hipchat
 - xmpp
 - flowdock
 - yammer
 - spark
 - irc
 - mattermost
 - matteruser
 - shell

# expects the "Get installed st2 version" task to run first.
st2_version_installed: "{{ _st2_version_installed.stdout }}"

# determines which version of node.js to install based on the installed st2
# The key is the st2 version (the newest version not > current version wins)
# The value is the nodejs_major_version to install
st2chatops_nodejs_versions:
  # 0-pad to preserve sorting
  '2.04': '6' # >=6, <7
  '2.10': '10' # >=8, <11

# The reject filter was added in Jinja 2.7, but CentOS 6 only has Jinja 2.6
#st2chatops_nodejs_major_version: "{{ st2chatops_nodejs_versions[ st2chatops_nodejs_versions.keys() | sort | reject('version', st2_version_installed, '>') | list | last ] }}"
# This stopped working with newer ansible. So we have to go with an older, harder to read if/else chain.
#_st2chatops_version: "{% set v = [] %}{% for st2v in st2chatops_nodejs_versions.keys() if st2v is version(st2_version_installed, '<=') %}{{ v.append(st2v) }}{% endfor %}{{ v | sort | last }}"
#st2chatops_nodejs_major_version: "{{ st2chatops_nodejs_versions[ _st2chatops_version ] }}"
st2chatops_nodejs_major_version: "{% if '2.10' is version(st2_version_installed, '<=') %}10{% elif '2.4' is version(st2_version_installed, '<=') %}6{% endif %}"
